language: R
r: release
cache: packages
sudo: required
pandoc_version: 1.19.2.1

git:
  depth: 5

branches:
  only: master

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

addons:
  apt:
    packages:
      - ghostscript
